spring.application.name=thigk2
server.port=8080

# ===== KET NOI SQL SERVER =====
spring.datasource.url=jdbc:sqlserver://DESKTOP-25TJO92\\BUITOCDO;databaseName=ThiGK2DB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@2tjoker2@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA / HIBERNATE =====
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
